
title: "ICLARS-CONF"
url: "https://itseg-mq.github.io" # GH Pages root
baseurl: "/website-iclars-conf"   # repo name
environment: "staging"            # env name
exclude:
  - editor-handbook.md
  - maintainer-handbook.md
